apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: docbridge-secret-provider
  namespace: docbridge
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "329dcdbf-b775-47d8-808b-d182f1e1d4d2"
    keyvaultName: "docbridge-dev-kv"
    tenantId: "ffdb5413-63c8-40ec-a158-c5ad34880e3d"
    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
        - |
          objectName: jwt-access-secret
          objectType: secret
        - |
          objectName: jwt-refresh-secret
          objectType: secret
        - |
          objectName: azure-openai-key
          objectType: secret
        - |
          objectName: redis-connection-string
          objectType: secret
  secretObjects:
    - secretName: docbridge-secrets
      type: Opaque
      data:
        - objectName: db-password
          key: DB_PASSWORD
        - objectName: jwt-access-secret
          key: JWT_ACCESS_SECRET
        - objectName: jwt-refresh-secret
          key: JWT_REFRESH_SECRET
        - objectName: azure-openai-key
          key: AZURE_OPENAI_KEY
        - objectName: redis-connection-string
          key: REDIS_CONNECTION_STRING
