apiVersion: v1
kind: ServiceAccount
metadata:
  name: docbridge-workload-sa
  namespace: docbridge
  annotations:
    azure.workload.identity/client-id: 329dcdbf-b775-47d8-808b-d182f1e1d4d2
  labels:
    azure.workload.identity/use: "true"
