apiVersion: v1
kind: Service
metadata:
  name: family-service-svc
  namespace: docbridge
spec:
  type: ClusterIP
  ports:
    - port: 3009
      targetPort: 3009
      protocol: TCP
  selector:
    app: family-service
