apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-services-to-gateway
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - auth-service
          - consultation-service
          - prescription-service
          - reminder-service
          - labreport-service
          - symptom-service
          - ai-companion-service
          - health-summary-service
          - family-service
          - db-migration
          - db-seeder
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: api-gateway
      ports:
        - protocol: TCP
          port: 3000
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
