apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-gateway-to-microservices
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - auth-service
          - consultation-service
          - prescription-service
          - reminder-service
          - labreport-service
          - symptom-service
          - ai-companion-service
          - health-summary-service
          - family-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: api-gateway
      ports:
        - protocol: TCP
          port: 3001
        - protocol: TCP
          port: 3002
        - protocol: TCP
          port: 3003
        - protocol: TCP
          port: 3004
        - protocol: TCP
          port: 3005
        - protocol: TCP
          port: 3006
        - protocol: TCP
          port: 3007
        - protocol: TCP
          port: 3008
        - protocol: TCP
          port: 3009
    - from:
        - podSelector:
            matchLabels:
              app: ai-companion-service
      ports:
        - protocol: TCP
          port: 3002
        - protocol: TCP
          port: 3003
        - protocol: TCP
          port: 3005
        - protocol: TCP
          port: 3006
        - protocol: TCP
          port: 3009
